Repository edgee-cloud/edgee, pull requests merged in 2024-08, with the labels that each got.

#24 docs: update README - copyediting & typos
  README.md
Labels: documentation, good first issue

#25 web.rs: fix invalid location header
  src/entrypoint/web.rs
Labels: bug, good first issue

#26 chore(deps): remove unused deps
  Cargo.lock
  Cargo.toml
Labels: good first issue, dependencies

#27 feat: support yaml config files
  Cargo.lock
  Cargo.toml
  README.md
  src/config.rs
Labels: enhancement

#28 feat: add config validations
  src/config.rs
Labels: enhancement
